# Generated by Django 4.2.4 on 2024-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
                ('aboutme', models.CharField(max_length=500)),
                ('teach_stack', models.CharField(max_length=1500)),
                ('education', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=1500)),
            ],
        ),
    ]
