# Generated by Django 4.2.4 on 2024-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='skill',
            field=models.TextField(),
        ),
    ]
