# Generated by Django 4.2.4 on 2024-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Introduction', '0002_alter_intro_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='aboutme',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='teach_stack',
            field=models.TextField(),
        ),
    ]
